<template>
    <div class="wh-wrap">
        <div class="wh-scroll">
            <!-- Hour scale -->
            <div class="wh-axis">
                <span class="wh-axis-spacer" />
                <span v-for="h in axisHours" :key="h" class="wh-axis-label mono">{{ h }}</span>
            </div>

            <!-- 7 rows (Monday~Sunday) × 24 columns (0-23 o'clock) matrix (button-like cells,
                 one Tab stop for the whole matrix) -->
            <div ref="gridRef" class="wh-matrix" role="group" :aria-label="t('chart.weekHour.aria')">
                <template v-for="(row, rowIdx) in weekMatrix" :key="rowIdx">
                    <span class="wh-row-label">{{ weekdayLabels[rowIdx] }}</span>
                    <div
                        v-for="(value, hour) in row"
                        :key="`${rowIdx}-${hour}`"
                        class="wh-cell"
                        :class="colorClass(value)"
                        role="button"
                        :tabindex="roving.tabIndex(rowIdx * 24 + hour)"
                        :aria-label="cellTooltip(rowIdx, hour, value)"
                        @click="onCellTap(rowIdx, hour, value, $event)"
                        @keydown="onCellKeydown($event, rowIdx * 24 + hour, rowIdx, hour, value)"
                        @focus="onCellFocus(rowIdx * 24 + hour, rowIdx, hour, value, $event)"
                        @blur="onCellBlur"
                        @pointerenter="onCellHover(rowIdx, hour, value, $event)"
                        @pointerleave="onCellLeave"
                    />
                </template>
            </div>
        </div>

        <!-- Cell info bubble (hover on desktop, tap on touch; the native title tooltip never appears on touch) -->
        <Teleport to="body">
            <Transition name="s2-tooltip">
                <div v-if="tipVisible" :ref="setTipEl" class="s2-tooltip s2-cell-tip" :style="tipStyle" role="tooltip">
                    {{ tipContent }}
                </div>
            </Transition>
        </Teleport>

        <!-- Legend -->
        <div class="wh-legend">
            <span class="wh-legend-label">{{ t('chart.legend.low') }}</span>
            <!-- Legend swatches carry only the legend class: the data-cell class brought a hover
                 outline and an opacity transition that a static swatch should not react to -->
            <span class="wh-legend-cell" :class="levelClass(0)" aria-hidden="true" />
            <span class="wh-legend-cell" :class="levelClass(1)" aria-hidden="true" />
            <span class="wh-legend-cell" :class="levelClass(2)" aria-hidden="true" />
            <span class="wh-legend-cell" :class="levelClass(3)" aria-hidden="true" />
            <span class="wh-legend-cell" :class="levelClass(4)" aria-hidden="true" />
            <span class="wh-legend-label">{{ t('chart.legend.high') }}</span>
        </div>
    </div>
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { LOCALE_DAYJS, resolveAppLocale } from '@/config/locales';
import { useDayjs } from '@/composables/useDayjs';
import { useCellTooltip } from '@/composables/useCellTooltip';
import { useRovingCells } from '@/composables/useRovingCells';
import { useHourlyProfile } from '@/composables/useHourlyProfile';
import { formatBytes } from '@/utils/bytes';

/**
 * 7×24 weekday × hour heatmap matrix.
 *
 * 7 rows (Monday~Sunday, row labels generated by dayjs localization) × 24 columns (0-23 o'clock),
 * with each cell colored across 5 levels by the historical average total traffic for that (weekday, hour) (cyan → blue → purple color-mix).
 * The matrix container scrolls horizontally on mobile, with a 10px minimum cell size.
 */
const { t, locale } = useI18n();
const dayjs = useDayjs();
const { weekMatrix } = useHourlyProfile();

/**
 * Row labels: Monday ~ Sunday (dayjs localized short names). `locale.value` is read so the computed
 * re-runs on a language switch (dayjs itself is not reactive).
 */
const weekdayLabels = computed(() => {
    const base = dayjs().locale(LOCALE_DAYJS[resolveAppLocale(locale.value)]);
    return Array.from({ length: 7 }, (_v, i) => base.day((i + 1) % 7).format('dd'));
});

/** Maximum value in the matrix (used for grading) */
const maxAvg = computed(() => weekMatrix.value.reduce((max, row) => Math.max(max, ...row), 0));

/** Bottom/top scale (one number every 4 hours) */
const axisHours = computed(() => Array.from({ length: 6 }, (_v, i) => i * 4));

/** 5 levels by average (0 = no data) */
function colorClass(value: number): string {
    return levelClass(levelOf(value, maxAvg.value));
}

/** Class name for each level */
function levelClass(level: number): string {
    return `wh-level-${level}`;
}

/** Level of the value relative to the maximum, on a square-root scale (0-4) */
function levelOf(value: number, max: number): number {
    if (value <= 0 || max <= 0) return 0;
    // Square-root scale: keeps small/medium cells distinguishable when one
    // outlier cell is much larger than the rest
    const ratio = Math.sqrt(value / max);
    if (ratio <= 0.25) return 1;
    if (ratio <= 0.5) return 2;
    if (ratio <= 0.75) return 3;
    return 4;
}

/** Build the cell tooltip */
function cellTooltip(rowIdx: number, hour: number, value: number): string {
    return t('chart.weekHour.cellTip', {
        weekday: weekdayLabels.value[rowIdx],
        time: `${String(hour).padStart(2, '0')}:00`,
        avg: formatBytes(value, 1).formatted,
    });
}

/**
 * Cell info bubble: hover shows it on desktop, tap shows it on touch, and a touch anywhere else
 * dismisses it. The selector is scoped to the matrix so the legend swatches do not count as cells.
 */
const {
    visible: tipVisible,
    content: tipContent,
    style: tipStyle,
    setTipEl,
    showForEl,
    hide: hideTip,
} = useCellTooltip('.wh-matrix .wh-cell');

/** The matrix is a single Tab stop; arrows walk the cells (Left/Right = ±1h, Up/Down = ±1 day) */
const gridRef = ref<HTMLDivElement>();
const roving = useRovingCells(gridRef, '.wh-matrix .wh-cell', () => weekMatrix.value.length * 24, {
    horizontal: 1,
    vertical: 24,
});

/** Hover shows the bubble on desktop only (touch also fires pointerenter on tap; the click path handles that) */
function onCellHover(rowIdx: number, hour: number, value: number, event: PointerEvent) {
    if (event.pointerType !== 'mouse') return;
    showForEl(event.currentTarget as HTMLElement, cellTooltip(rowIdx, hour, value));
}

function onCellLeave(event: PointerEvent) {
    if (event.pointerType !== 'mouse') return;
    hideTip();
}

/** Tap (or mouse click; the cells have no other action) shows the bubble against the cell */
function onCellTap(rowIdx: number, hour: number, value: number, event: MouseEvent) {
    showForEl(event.currentTarget as HTMLElement, cellTooltip(rowIdx, hour, value));
}

function onCellKeydown(event: KeyboardEvent, i: number, rowIdx: number, hour: number, value: number) {
    if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        showForEl(event.currentTarget as HTMLElement, cellTooltip(rowIdx, hour, value));
        return;
    }
    roving.onKeydown(event, i);
}

/** Keyboard focus shows the same bubble hover would */
function onCellFocus(i: number, rowIdx: number, hour: number, value: number, event: FocusEvent) {
    roving.syncActive(i);
    showForEl(event.currentTarget as HTMLElement, cellTooltip(rowIdx, hour, value));
}

function onCellBlur() {
    hideTip();
}
</script>

<style scoped>
.wh-wrap {
    user-select: none;
}

.wh-scroll {
    overflow-x: auto;
}

.wh-axis {
    display: grid;
    /* Same column geometry as .wh-matrix so each scale label sits exactly above its hour column */
    grid-template-columns: 30px repeat(24, minmax(14px, 1fr));
    gap: 3px;
    margin-bottom: 4px;
    min-width: 560px;
}

.wh-axis-label {
    grid-column: span 4;
    font-size: 10px;
    color: var(--s2-text-muted);
}

.wh-matrix {
    display: grid;
    grid-template-columns: 30px repeat(24, minmax(14px, 1fr));
    grid-auto-rows: 20px;
    gap: 3px;
    align-items: stretch;
    min-width: 560px;
}

.wh-row-label {
    font-size: 11px;
    color: var(--s2-text-muted);
    line-height: 20px;
    font-family: var(--font-sans);
}

.wh-cell {
    border-radius: 3px;
    transition:
        opacity 0.15s,
        background-color var(--s2-transition);
}

.wh-cell:hover {
    opacity: 0.75;
    outline: 1px solid var(--s2-text-muted);
    outline-offset: -1px;
}

.wh-cell:focus-visible {
    opacity: 1;
    outline: 2px solid var(--brand);
    outline-offset: 1px;
}

.wh-legend {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 3px;
    margin-top: 8px;
}

.wh-legend-label {
    font-size: 11px;
    color: var(--s2-text-muted);
    margin: 0 2px;
}

.wh-legend-cell {
    display: inline-block;
    width: 12px;
    height: 12px;
    border-radius: 3px;
}

/* Color levels (light) — cyan → blue → purple duotone scale */
.wh-level-0 {
    background-color: var(--s2-border-light);
}
.wh-level-1 {
    background-color: color-mix(in srgb, var(--cyan) 35%, var(--s2-border-light));
}
.wh-level-2 {
    background-color: color-mix(in srgb, var(--rx) 55%, var(--s2-border-light));
}
.wh-level-3 {
    background-color: color-mix(in srgb, var(--purple) 75%, var(--s2-border-light));
}
.wh-level-4 {
    background-color: var(--purple);
}

@media (--mobile) {
    .wh-matrix {
        grid-template-columns: 26px repeat(24, minmax(10px, 1fr));
        grid-auto-rows: 14px;
        gap: 2px;
        min-width: 0;
    }
    .wh-axis {
        grid-template-columns: 26px repeat(24, minmax(10px, 1fr));
        gap: 2px;
        min-width: 0;
    }
    .wh-row-label {
        font-size: 10px;
        line-height: 14px;
    }
}
</style>

<style>
/* WeekHourHeatmap dark mode — global scope so :root.dark can override it */
:root.dark .wh-level-0 {
    background-color: var(--s2-border-light);
}
:root.dark .wh-level-1 {
    background-color: color-mix(in srgb, var(--cyan) 35%, var(--s2-bg));
}
:root.dark .wh-level-2 {
    background-color: color-mix(in srgb, var(--rx) 55%, var(--s2-bg));
}
:root.dark .wh-level-3 {
    background-color: color-mix(in srgb, var(--purple) 75%, var(--s2-bg));
}
:root.dark .wh-level-4 {
    background-color: color-mix(in srgb, var(--purple) 90%, var(--s2-text));
}
</style>
